### ISSUE TITLE
Include  information on triggers

### ISSUE THREAD

**Issue by lrweck** [pgMustard/pgMustard#22]
I wasn't able to find any information on triggers.

In PEV2 I can see which trigger has been run, how long did it take, how many times it was called and more:
![image](https://user-images.githubusercontent.com/26086198/69053070-52d4e200-09e7-11ea-8f7a-972f0b5d3f30.png)

**Comment by mchristofides** [comment]
Sorry, we don't include information related to triggers (or planning time) yet. 

While we have seen performance issues be related to them, they have been much rarer than the things we currently have tips for, so they haven't made it to the top of our list quite yet.

They're definitely something we want to do though, thanks for submitting this!

If or when you come across examples where they're one of the limiting factors, please do send them over! These will really help when we come to implementing this. 🙌

**Comment by lrweck** [comment]
Hey Michael!

It really depends on the workload. For SELECT only it wouldn't really be an issue. For any DML it can point to a problem in the trigger itself (no indexes, large loops, etc).

I had a problem a few months ago where we were using a trigger on a small table (only one row) which was heavily updated and had a trigger. Turns out, the trigger itself wasn't really needed. I managed to find this problem because the trigger text was showing up enough in _pg_stat_statements_ that it was among the top "total time spent" queries.

**Comment by mchristofides** [comment]
@lrweck thought you might be pleased to know we have released a version of pgMustard with Trigger times and also links to the operations that likely caused them to fire.

Here is what it looks like for your example above:

![image](https://user-images.githubusercontent.com/10532911/100752090-0d136d80-33e0-11eb-999e-16aa6a048e04.png)

As ever, feedback very welcome. I'll close this issue for now, but feel free to comment and/or submit others.
