### ISSUE TITLE
Better handling of very large (MBs) query plans

### ISSUE THREAD

**Issue by hairybreeches** [pgMustard/pgMustard#36]
One user says:

"My query plan is roughly 3mb.

The first execution always works fine, with a second query plan there's always an error bubble saying' unable to save results to a local storage'. After that I clean up the local storage by deleting all k/v pairs. 
Execution of a query leads to an error but a second submit is successful."

This situation is rare, but could be handled better, for example subsequent attempts should work after local storage has been cleared.

This issue will go away if we do decide to move to server-side storage

**Comment by hairybreeches** [comment]
After getting more information, it seems like the failed requests might be to do with an overzealous proxy server, but it would still be good to support very large plans better!

**Comment by davegudge** [comment]
I've just used up the 5 free tries and each time I was presented with: 

<img width="1206" alt="Screenshot 2021-09-09 at 21 43 04" src="https://user-images.githubusercontent.com/1736807/132759923-b8559b8c-e710-4b78-b4d6-10cc1167f1f3.png">

The json file was 5.1MB.

**Comment by mchristofides** [comment]
@davegudge thank you and apologies – as a starting point I've reset those credits and added a few more in case you hit it again. 

Which browser and OS are you on? Are you able to try another browser? (Some have larger local storage limits than others.)

There's a chance you're only sneaking over a limit at 5.1MB, so another thing to try in the short term is removing the COSTS, which I don't think we use for any of the tips. eg `EXPLAIN (COSTS OFF, ANALYZE, VERBOSE, BUFFERS, FORMAT JSON)` 

A heavier handed option is to turn off the VERBOSE parameter, but that data is used for some of the tips, so a less good option sadly.

**Comment by davegudge** [comment]
Thanks for the response and for the credit reset. 

I only found out about pgMustard this evening after reading https://blog.testdouble.com/posts/2021-09-09-how-to-build-a-search-engine-with-ruby-on-rails/. Ive watched the YouTube example https://www.youtube.com/watch?v=v7ef4Fpn2WI and it looks like an incredible tool 😍

The query I am running is a beast to be fair! I was attempting to optimise it earlier this week. 

I started off using pgMustard in Chrome and then I switched over to Firefox. I got the same issue in both browsers. 

Thanks for the tip; I'll give it a try tomorrow with the costs set to off.

**Comment by mchristofides** [comment]
Thanks for the kind words! Justin’s post is great isn’t it. His tweets [1](https://twitter.com/searls/status/1402991961741545479) [2](https://twitter.com/searls/status/1406305001190866948) about pgMustard a while ago resulted in quite a few new people finding us, he’s definitely better at getting the word out than we are. 😅

I’ve just remembered that, mostly to enable the publishing feature, we now store both the input and output in local storage. So there’s a chance we’re exceeding even a 10MB limit in the case of this plan. We have seen plans bigger though, I think as much as 13MB, so we know we need a better solution.

Best of luck on the query tomorrow, do let me know if I can help.

**Comment by hairybreeches** [comment]
I think that because we add quite a bit of info to the input, our output is always significantly larger than the input, so I wouldn't worry too much about the exact size of the input, although it's always good to know a ballpark figure.

I think we have roughly three different options to resolve this:

1) Don't store the output when it's too large. So larger plans will still work, but won't appear in the history, or be recoverable without processing the plan again. This is simple to implement, and keeps a lot of the benefits of history, but it does mean the behaviour is a bit unpredictable and hard to understand.

2) Stop storing plans in local storage altogether, and get rid of the history. Some of the benefits of the history are reduced now we have publishing, but there is still a possibility that people (particularly trialists) will want to return to previous plans without either re-inputting them, or making them completely public (something I do want to discourage becoming routine)

3) Store the plans on the server, instead. I honestly don't love this, because I feel like people have a good understanding of how sensitive this data can be and value our decision not to hang onto it unless they allow us to. We could make it only happen "sometimes" (eg as a different sort of publish, be togglable at the account level, or only when the plan is very large, or saving to local storage fails), and could possibly coexist with history.

**Comment by mchristofides** [comment]
@hairybreeches nice one. I was wondering whether compressing the input and/or output could be an option?

**Comment by hairybreeches** [comment]
> @hairybreeches nice one. I was wondering whether compressing the input and/or output could be an option?

Yeah, it absolutely is. I suspect that the format of our data means that it will compress really well and therefore hugely expand the amount of plans we can deal with.

I guess it does mean that some plans could still be too big, so it doesn't resolve absolutely all cases, however we might end up with a sufficient compression rate that in practice, this isn't really an issue any more. What's the biggest we've seen? Do I remember one over 100MB?

The other drawback to this approach is that it does add just that extra barrier to debugging/exploration. Quite small for us (since we do the encoding so will have the decoding fns to hand) but a bit bigger for anyone looking to understand what's in their local storage. Probably not big enough to change our decision but still a factor.

**Comment by mchristofides** [comment]
Oh cool! I'm hopeful on the compression rate too.

I don't remember a 100MB one(!) The largest stored plan I remember was ~13MB... still big, but I think it might make it a non-issue in practice.

Good point on the debugging front, I did [once](https://twitter.com/pgMustardApp/status/1403116887429586946) point somebody to the input, but only once so far. If we want to in future, I guess we could add a way to decode and view the input in the UI?

**Comment by hairybreeches** [comment]
I've deployed an update that uses compression when storing plans (commit a9d8603c266487466dbfa3624e3644c92f33a91b, deployed on 27/9/21, 12:11 UTC). It seems to solve the problem for the large plans I have access to for testing purposes.

I'm going to close this for now, if anyone still has problems, feel free to reopen.

Sorry for taking such a long time fixing this @davegudge , hope this solves the issue!

**Comment by hairybreeches** [comment]
Oops, my mistake, it's still deploying...

**Comment by davegudge** [comment]
Thanks for the update @hairybreeches. I haven't actually made it back onto the task I was working on when I commented on this issue, but I'll certainly give pgMustard another try when I do. 👍🏼

**Comment by hairybreeches** [comment]
Update: I had to roll back the change, something went wrong with the js compilation that I wasn't experiencing on a local build, unfortunately. Will update again when it goes live for good!

**Comment by mchristofides** [comment]
@davegudge heads up that this is now live and (seemingly) not broken this time. Once you get back to that task, it'd be great to hear how you get on. Thanks for the prompt and encouragement to get this done!

**Comment by davegudge** [comment]
Thanks for the info @mchristofides. I'll be sure to utilise pgMustard once I move back onto the optimisation task.
