### ISSUE TITLE
Can't parse plan

### ISSUE THREAD

**Issue by lrweck** [pgMustard/pgMustard#42]
Hey guys!

here's a plan that is not being recognized as a valid PG plan:

[https://pastebin.com/LyJ6Kc31](https://pastebin.com/LyJ6Kc31)

**Comment by mchristofides** [comment]
Hey Luís!

Which version of PostgreSQL are you using here? The buffers details for the planning make me think it's 13+, but do say if I've misunderstood. We haven't added support for the new explain features in 13 just yet.

It looks like for this plan, replacing the "Planning" array with just the key for "Planning Time" can get it working in pgMustard, but naturally with the caveat that we might be missing other newly added information too.

**Comment by lrweck** [comment]
Hi!, yes, you're right. I forgot to mention it was v13. Doing what you said managed to parse to plan.

Thanks for the reply!

**Comment by hairybreeches** [comment]
An update: this issue is now fixed and this sort of plan should now work.

This was caused by a naming clash - v13 adds a planning node under the key "planning" - which is exactly what pgMustard does under the hood.
