### ISSUE TITLE
"Error setting value in local storage." after buying pro subscription

### ISSUE THREAD

**Issue by MathiasVersichele** [pgMustard/pgMustard#46]
I get the above error when trying to analyze a query plan after buying a subscription. I get the following message:

_This can happen when local storage is full. pgMustard uses local storage to store your query plans, including for reference via the History tab. You can try clearing local storage and submitting again, but please be aware that this will remove previously submitted query plans._

No idea how to do this + I just bought a subscription so I expect it to "just work".

**Comment by MathiasVersichele** [comment]
Worked in another browser

**Comment by mchristofides** [comment]
@MathiasVersichele welcome, and sorry you hit this straight after subscribing! Also I’m glad you found a workaround already too.

For a bit of context, pgMustard currently stores up to 10 of your most recent plans in local browser storage for the History tab, in case you need them again soon. It should replace older ones with newer ones when low on space, but if this fails the error you saw is shown. We could do with some help reproducing this, so when you get a moment any context on which browser you were using and how big the plan was would be very welcome!

Thanks for subscribing and for submitting this, do let us know if anything else could be improved.

**Comment by mchristofides** [comment]
For posterity, this issue should be far less likely in future, as pgMustard now compresses query plans (shipped as #36 ).
