### ISSUE TITLE
Changing your email address on Github results in a new pgMustard account

### ISSUE THREAD

**Issue by willcosgrove** [pgMustard/pgMustard#53]
I recently changed my primary email address associated with my Github account, and I noticed that when I tried to sign in to PG Mustard with my Github account, I was treated as a new user, and I am unable to access my account that has the Pro membership.

**Comment by mchristofides** [comment]
@willcosgrove apologies for the rubbish experience on this. I've shot you a quick email to verify, and added a bunch of credits in case helpful in the meantime.
