### ISSUE TITLE
Submit different versions of a query

### ISSUE THREAD

**Issue by mchristofides** [pgMustard/pgMustard#60]
"Like explain.depesz.com it would be nice to be able to submit optimizations or different versions of a query I've tried and group them under the same history node."

Originally suggested in https://github.com/pgMustard/pgMustard/issues/32

**Comment by mchristofides** [comment]
While not perfect, the plan name is now displayed in a couple more places (#67), which should help a little with this.

**Comment by prenagha** [comment]
at its core quite similar to the compare idea #33

**Comment by mchristofides** [comment]
We've started work on a simple first version of adding optimizations! Here’s the simplest implementation we could imagine:

1. Let people add an optimization from an existing plan
2. Once a plan has at least one optimization, add a link to an optimizations page for that plan
3. The optimizations page looks like the History page, but is ordered with the parent plan first, then the optimization plans in chronological order (not reverse chronology, so the opposite of the History sort order)

See below for what we're thinking 1, 2, and 3 could look like.

We're looking for a few people to discuss this with before finalizing the details — please [book a time to talk here](https://savvycal.com/pgmustard/optimization-workflow)! 



![Image](https://github.com/pgMustard/pgMustard/assets/10532911/c93beeef-0635-492d-a350-8bf96f26885b)

**Comment by mchristofides** [comment]
Thanks to several conversations, we found out people cared more about linking the plans than any calculations, so for now we've shipped a simple first version of this that simply allows adding a plan as an optimization of another plan, and then viewing them together, very similar to the designs above.

Here's an example:

https://app.pgmustard.com/#/optimizations/fffa51d9-a210-44bd-9f7a-7c52984a2c37



![Image](https://github.com/user-attachments/assets/ce24e67c-9919-4065-9594-438b39e73e8e)
