### ISSUE TITLE
not able to process the file tried two times, its 49 MB

### ISSUE THREAD

**Issue by ramadasara** [pgMustard/pgMustard#64]
![image](https://user-images.githubusercontent.com/10901369/227068792-a4479b83-94f5-4ad3-a1f4-e6c7a3cbd2b9.png)

not able to process the file tried two times, its 49 MB

**Comment by mchristofides** [comment]
@ramadasara thanks for reporting and sorry for the issue, I’ll look into it tomorrow. In the meantime, you could try generating a plan without alignment (eg whitespace and line ending characters added by psql). You can toggle that in psql with \a (or the -A option). This may be much smaller, and avoiding tripping something up on our side (49MB is close to the largest plan I’ve seen!)

**Comment by ramadasara** [comment]
Hi  Michael,

Do you have an offline version of pgMustard which I can purchase, also is
there a way to save the html report for offline  use and distribution to
dev team

Regards

**Comment by mchristofides** [comment]
@ramadasara I'm afraid we only offer an online version at the moment, but I'll make a note to let you know if that changes. 

We don't log much, but it looks like you might have got this working? In any case, I've reset your trial credits as I believe you may have lost one or two with this error.
