### ISSUE TITLE
 Ability to change share setting

### ISSUE THREAD

**Issue by prenagha** [pgMustard/pgMustard#69]
It would be useful to be able to change the share level. For example I set to visible by those with link, share with colleagues, then a week later want to change it back to  private.
Or vice versa.
Currently it seems I have to delete the plan and add as new plan to do so.

And/or an option to make shareable with public link for X days, X hours...

**Comment by mchristofides** [comment]
@prenagha this is already possible, albeit a little hidden — if you go to the History page, the three dots on the right hand side of each row will let you edit the settings. 

The limited time option idea is interesting too, would you ideally want plans to get deleted after a certain time, or just switch back to a more private storage option?

**Comment by prenagha** [comment]
I'd want mostly to switch back to private.
Not a bad idea to also have a global "purge after X days" as well.

**Comment by mchristofides** [comment]
Great, thank you! 

There are some valid use cases for never purging some plans, like folks have included them in blog posts, online books, and training materials. I think some people that use the links in PRs would prefer them never to be deleted (or at least for it to be measured in years). We'll have a think about whether to add this as an option, thanks again

**Comment by mchristofides** [comment]
@prenagha we've now added a button so that you can change the share level without having to go to the history page:

![image](https://github.com/pgMustard/pgMustard/assets/10532911/3445def9-f31c-42eb-ac10-748bd51ea71d)
