### ISSUE TITLE
Feature request: add tip type for slow foreign key cascading triggers

### ISSUE THREAD

**Issue by aristocrates** [pgMustard/pgMustard#72]
I ran into slow deletes on a table recently and uploaded an explain plan (using a query similar to the following):

```sql
BEGIN;
SET LOCAL statement_timeout = 0;
EXPLAIN (analyze, buffers, verbose, format json) DELETE FROM "photos" WHERE "photos"."id" = ?;
ROLLBACK;
```

The root cause of the slowness ended up being a missing index on the referencing column of a foreign key constraint [1] which made the cascading `ON DELETE SET NULL` slow, but there weren't any tips from pgMustard drawing attention to the `photos_parent_id_fkey` trigger (#T4) - even though it took 75 seconds, several orders of magnitude longer than the other operations.

![slow_cascading_delete_due_to_self_referential_fkey](https://github.com/pgMustard/pgMustard/assets/4792145/cfbf5afb-54be-436c-9532-d5ef444a5cd1)

It would be helpful if pgMustard called attention to a trigger when it is a clear outlier in time taken compared to everything else - and in the event of a string match on "fkey" in the constraint name it would be nice to recommend auditing for whether an index exists on the referencing column, and if not to create an index on the referencing column and see if that improves performance [2] [3].

[1] in this case, a self-reference from the "photos" table to itself across a couple of columns; probably a holdover from emulating the `parent_id` pattern in https://github.com/technoweenie/attachment_fu
[2] "99% of the time, the cause [of slow cascading deletes related to foreign keys] is lack of an index on the foreign key's referencing columns." https://www.postgresql.org/message-id/1905752.1705443374%40sss.pgh.pa.us
[3] https://www.pgmustard.com/blog/trigger-time

**Comment by mchristofides** [comment]
@aristocrates great suggestion, thank you! I've been wanting to add this for a while but it hasn't quite made it to the top of the list yet. I'll keep you posted with any progress

**Comment by mchristofides** [comment]
@aristocrates we've shipped a new tip for Triggers, that includes giving some foreign-key-specific advice in cases like the one you mention. Thanks again for the suggestion and details! 

Here's a simple example: 
![Image](https://github.com/user-attachments/assets/946803c0-0bb3-43ce-8618-7230d5c5c245)
